# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_NAME: simple-java-maven-app
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
# Use Java 21 because of the Maven Enforcer rule
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'
        
# ---- PRE-IMAGE TESTS ----
    - name: Run unit tests
      run: mvn -B -q test
    
    - name: versioning
      id: version
      run: |
          PATCH=${GITHUB_RUN_NUMBER}
          VERSION="1.0.${PATCH}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Building version $VERSION"
  

    
    - name: Build Docker image
      run: |
        VERSION=${{ steps.version.outputs.version }}
        IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}

        docker build \
          --build-arg APP_VERSION=${VERSION} \
          -t ${IMAGE}:${VERSION} \
          -t ${IMAGE}:latest \
          
